name: Flutter Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy Flutter Web

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Forçar a instalação do Flutter
      - name: Install Flutter manually
        run: |
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          export PATH="$PATH:`pwd`/flutter/bin"
          flutter doctor

      # Configurar o Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"

      # Build do Flutter Web
      - name: Build Flutter Web
        run: flutter build web --release

      # Deploy para Azure
      - name: Deploy Static Web App
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "build/web"
          api_location: ""
